name: Publish artifacts to Sonatype
description: Publishes artifacts to Sonatype

inputs:
  version:
    description: "Version of client to build"
    required: true
  crypto-type:
    description: Crypto type. This should either be bouncycastle or gnu
    required: true
  maven-username:
    description: Maven repo username
    required: true
  maven-token:
    description: Maven repo password
    required: true
  gpg-sigining-key:
    description: GPG private signing key
    required: true
  gpg-signing-key-password:
    description: GPG private signing key password
    required: true
  module:
    description: Module to publish
    required: true

runs:
  using: "composite"
  steps:
    - name: Set version
      shell: bash
      run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}

    - name: Build
      shell: bash
      run: |
        mvn clean install -Dcrypto.type=${{ inputs.crypto-type }}

    - name: Build source jar
      run: mvn source:jar
      shell: bash
      working-directory: ${{ inputs.module }}

    - name: Build docs
      run: mvn javadoc:jar
      shell: bash
      working-directory: ${{ inputs.module }}

    - name: Debug list content
      shell: bash
      run: ls -R target
    #- name: Publish package
    #  working-directory: ${{ inputs.module }}
    #  shell: bash
    #  run: mvn -P release --batch-mode deploy -DskipTests
    #  env:
    #    MAVEN_USERNAME: ${{ inputs.maven-username }}
    #    MAVEN_PASSWORD: ${{ inputs.maven-token }}
    #    MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-signing-key-password }}
