on:
  workflow_call:
    inputs:
      base-branch:
        type: string
        required: true
      java-version:
        type: number
        required: true
      client-type:
        type: string
        required: true
        description: "Crypto type. Can be be either bouncycastle or gnu."
    secrets:
      - SONATYPE_MAVEN_USERNAME
      - SONATYPE_MAVEN_PASSWORD
      - MAVEN_GPG_SIGNING_KEY
      - MAVEN_GPG_PASSPHRASE

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_IDENTIFIER: "${{ inputs.base-branch }}-${{ inputs.java-version }}-${{ inputs.client-type }}"
    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.base-branch }}

      - name: Set crypto
        if: ${{ inputs.client-type == 'gnu' || inputs.client-type == 'bouncycastle' }}
        run: |
          ./.github/workflows/scripts/set_crypto.sh ${{ inputs.client-type }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}
          server-username: ${{ secrets.SONATYPE_MAVEN_USERNAME }}
          server-password: ${{ secrets.SONATYPE_MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_SIGNING_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Echo new version to CI
        id: get-new-version
        run: echo new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Release client
        uses: ./.github/actions/upload-to-sonatype
        with:
          version: ${{ needs.get-new-version.outputs.new_version }}
          maven-username: ${{ secrets.SONATYPE_MAVEN_USERNAME }}
          maven-password: ${{ secrets.SONATYPE_MAVEN_PASSWORD }}
          gpg-signing-key: ${{ secrets.MAVEN_GPG_SIGNING_KEY }}
          gpg-signing-key-password: ${{secrets.MAVEN_GPG_PASSPHRASE }}
          module: client

      - name: Release proxy client
        if: ${{ inputs.java-version == 8 }}
        uses: ./.github/actions/upload-to-sonatype
        with:
          version: ${{ needs.get-new-version.outputs.new_version }}
          maven-username: ${{ secrets.SONATYPE_MAVEN_USERNAME }}
          maven-password: ${{ secrets.SONATYPE_MAVEN_PASSWORD }}
          gpg-signing-key: ${{ secrets.MAVEN_GPG_SIGNING_KEY }}
          gpg-signing-key-password: ${{secrets.MAVEN_GPG_PASSPHRASE }}
          module: client
