on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      use-server-rc:
        type: boolean
        required: false
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: false
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: false
        default: false
        description: "Upload built artifacts to github?"

jobs:
  build-java-21:
    if: ${{ inputs.branch == 'refs/heads/stage' }}
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [21]
        include:
          - java-version: 21
            branch: "stage"
    with:
      branch: ${{ matrix.branch }}
      bump-version: false
      use-server-rc: ${{ inputs.server-rc }}
      server-tag: ${{ inputs.server.tag }}
      upload-artifacts: ${{ inputs.upload-artifacts }}

  build-java-8:
    if: ${{ inputs.branch == 'refs/heads/stage-jdk8' }}
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [8]
        include:
          - java-version: 8
            branch: "stage-jdk8"
    with:
      java-version: ${{ matrix.java-version }}
      branch: ${{ matrix.branch }}
      bump-version: false
      use-server-rc: ${{ inputs.server-rc }}
      server-tag: ${{ inputs.server.tag }}
      upload-artifacts: ${{ inputs.upload-artifacts }}
