name: Build artifacts

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      java-version:
        type: number
        required: true
      bump-version:
        type: boolean
        required: false
        default: false
      use-server-rc:
        type: boolean
        required: true
        default: false
        description: "Test against server release candidate?"
      server-tag:
        type: string
        required: true
        default: "latest"
        description: "Server docker image tag"
      upload-artifacts:
        type: boolean
        required: true
        default: false
        description: "Upload built artifacts to github?"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_IDENTIFIER: "${{ inputs.branch }}-${{ inputs.java-version }}"
    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}

      - name: Increment version
        if: ${{ inputs.bump-version == true }}
        run: |
          mvn build-helper:parse-version versions:set \
          -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.nextMinorVersion}.\${parsedVersion.incrementalVersion} \
          versions:commit

      - name: Run EE server
        uses: ./.github/actions/run-ee-server
        with:
          use-server-rc: ${{ inputs.use-server-rc }}
          server-tag: ${{ inputs.server-tag }}

      - name: Build
        run: mvn install

      - name: Test
        working-directory: test
        run: mvn test

      - name: Upload jars to GitHub
        if: ${{  !cancelled() && inputs.upload-artifact == true }}
        uses: actions/upload-artifact@v4
        with:
          path: ./*/target/*.jar
          name: ${{ env.BUILD_IDENTIFIER }}.build
