on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
        description: input branch

jobs:
  build-java-21:
    if: ${{ inputs.branch == 'refs/heads/stage' }}
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [21]
        include:
          - java-version: 21
            branch: "stage"
    with:
      java-version: ${{ matrix.java-verision }}
      branch: ${{ matrix.branch }}
      bump-version: false

  build-java-8:
    if: ${{ inputs.branch == 'refs/heads/stage-jdk8' }}
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [8]
        include:
          - java-version: 8
            branch: "stage-jdk8"
    with:
      java-version: ${{ matrix.java-version }}
      branch: ${{ matrix.branch }}
      bump-version: false
