on:
  workflow_call:
    inputs:
      base-branch:
        type: string
        required: true
      java-version:
        type: number
        required: true
      major:
        type: number
        required: true
        description: ""
      minor:
        type: number
        required: true
        description: ""
      patch:
        type: number
        required: true
        description: ""
      client-type:
        type: string
        required: true
        description: "Crypto type. Can be be either bouncycastle or gnu."

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_IDENTIFIER: "${{ inputs.branch }}-{{ inputs.java-version }}"
    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.base-branch }}

      - name: Set crypto
        if: ${{ inputs.client-type == 'gnu' || inputs.client-type == 'bouncycastle' }}
        run: |
          ./.github/workflows/scripts/set_crypto.sh ${{ inputs.client-type }}

      #- name: Get java version
      #  run: |
      #    mvn -version
      #    java -version

      #- name: Setup Java
      #  uses: actions/setup-java@v4
      #  with:
      #    distribution: "semeru" # See 'Supported distributions' for available options
      #    java-version: ${{ inputs.java-version }}

      #- name: Set crypto
      #  if: ${{ inputs.client-type == 'gnu' || inputs.client-type == 'bouncycastle' }}
      #  run: |
      #    ./.github/workflows/scripts/set_crypto.sh ${{ inputs.client-type }}

      #- name: Increment version
      #  run: |
      #    mvn versions:set \
      #    -DnewVersion=${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }} \
      #    versions:commit

      #- name: Echo new version to CI
      #  id: get-new-version
      #  run: echo new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      #- name: Commit new version
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: "Auto-bump version to ${{ steps.get-new-version.outputs.new_version }} [skip ci]"
      #    commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      #    tagging_message: ${{ steps.get-new-version.outputs.new_version }}
      #    branch: ${{ inputs.is_workflow_call && github.ref }}

      - name: Build
        run: |
          mvn clean install

      - name: Build source jar
        run: |
          mvn source:jar
        working-directory: client

      - name: Build docs
        run: |
          mvn javadoc:jar
        working-directory: client

      - name: Package
        uses: ./.github/actions/package-jar
        with:
          version: ${{ inputs.new_version }}
          jdk: ${{ inputs.java-version == 21 && 'jdk21' || 'jdk8' }}
          extension: ${{ inputs.client-type == 'bouncycastle' && '-bc' || '' }}

      - name: Upload jars to GitHub
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          path: ./pkg/*.jar
          name: ${{ env.BUILD_IDENTIFIER }}.build
