on:
  workflow_call:
    inputs:
      base-branch:
        type: string
        required: true
      java-version:
        type: number
        required: true
      client-type:
        type: string
        required: true
        description: "Crypto type. Can be be either bouncycastle or gnu."
    secrets:
      SONATYPE_MAVEN_USERNAME:
        required: true
      SONATYPE_MAVEN_PASSWORD:
        required: true
      GPG_SECRET_KEY:
        required: true
      GPG_PASS:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base-branch }}

      - name: Set crypto
        if: ${{ inputs.client-type == 'gnu' || inputs.client-type == 'bouncycastle' }}
        run: |
          ./.github/workflows/scripts/set_crypto.sh ${{ inputs.client-type }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}
          server-username: ${{ secrets.SONATYPE_MAVEN_USERNAME }}
          server-password: ${{ secrets.SONATYPE_MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASS }}

      - name: Echo new version to CI
        id: get-new-version
        run: echo new_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Release client
        uses: ./.github/actions/upload-to-sonatype
        with:
          version: ${{ steps.get-new-version.outputs.new_version }}
          maven-username: ${{ secrets.SONATYPE_MAVEN_USERNAME }}
          maven-token: ${{ secrets.SONATYPE_MAVEN_PASSWORD }}
          gpg-signing-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-signing-key-password: ${{secrets.GPG_PASS }}
          module: client
          crypto-type: ${{ inputs.client-type == 'bouncycastle' && '-bc' || '' }}

      - name: Release proxy client
        if: ${{ inputs.java-version == 8 }}
        uses: ./.github/actions/upload-to-sonatype
        with:
          version: ${{ steps.get-new-version.outputs.new_version }}
          maven-username: ${{ secrets.SONATYPE_MAVEN_USERNAME }}
          maven-token: ${{ secrets.SONATYPE_MAVEN_PASSWORD }}
          gpg-signing-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-signing-key-password: ${{secrets.GPG_PASS }}
          module: client
          crypto-type: ""
