name: Build artifacts

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      java-version:
        type: number
        required: true
      build-identifier:
        type: string
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_IDENTIFIER: "${{ inputs.branch }}-{{ inputs.java-version }}-${{ inputs.build-identifier}}"
    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}

      - name: Run EE server
        uses: ./.github/actions/run-ee-server
        #with:
        #  use-server-rc: ${{ inputs.use-server-rc }}
        #  server-tag: ${{ inputs.server-tag }}

      - name: Build and test
        run: |
          mvn install
          cd test
          mvn test -DskipTests=false

      - name: Upload jars to GitHub
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          path: ./*/target/*.jar
          name: ${{ env.BUILD_IDENTIFIER }}.build
