on:
  workflow_call:
    inputs:
      major:
        type: number
        required: true
        description: ""
      minor:
        type: number
        required: true
        description: ""
      patch:
        type: number
        required: true
        description: ""
      branch:
        type: string
        required: true
        description: input branch

jobs:
  build-java-21:
    uses: ./.github/workflows/build-release.yaml
    strategy:
      matrix:
        java-version: [21]
        include:
          - java-version: 21
            branch: "master"
            client-type: ["gnu", "bouncycastle"]
    with:
      java-version: ${{ matrix.java-verision }}
      base-branch: ${{ matrix.branch }}
      major: ${{ inputs.major }}
      minor: ${{ inputs.minor }}
      patch: ${{ inputs.patch }}
      client-type: ${{matrix.client-type }}

  build-java-8:
    uses: ./.github/workflows/build-release.yaml
    strategy:
      matrix:
        java-version: [8]
        include:
          - java-version: 8
            branch: "jdk8"
            client-type: ["gnu", "bouncycastle", "proxy"]
    with:
      java-version: ${{ matrix.java-version }}
      base-branch: ${{ matrix.branch }}
      major: ${{ inputs.major }}
      minor: ${{ inputs.minor }}
      patch: ${{ inputs.patch }}
      client-type: ${{matrix.client-type }}
