name: Pull `request open` stage build workflow (WIP)

on:
  pull_request:
    branches:
      - "stage*"
    types:
      - review_requested
  workflow_dispatch:

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: github.ref
