name: Pull `request open` stage build workflow (WIP)

on:
  pull_request:
    branches:
      - "stage*"
    types:
      - review_requested
  workflow_dispatch:

jobs:
  build:
    name: Build stage
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: github.ref

  # Clean up after files artifacts have been uploaded to jfrog
  delete-artifacts:
    needs: "build-stage"
    name: Delete artifacts
    uses: ./.github/workflows/delete-artifacts.yaml
