name: Pull `request closed` stage build workflow (WIP)

on:
  pull_request_target:
    branches:
      - stage
      - stage-jdk8
    types:
      - closed
  workflow_dispatch:

jobs:
  build-stage:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [21]
        include:
          - java-version: 21
            branch: "stage"
    with:
      java-version: ${{ matrix.java-verision }}
      branch: ${{ matrix.branch }}
      bump-version: true

  build-stage-jdk8:
    if: github.ref == 'refs/heads/stage-jdk8'
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [8]
        include:
          - java-version: 8
            branch: "stage-jdk8"
    with:
      java-version: ${{ matrix.java-version }}
      branch: ${{ matrix.branch }}
      bump-version: true

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      version: ${{ needs.bump-dev-number.outputs.new_version }}
    secrets: inherit

  # Clean up after files artifacts have been uploaded to jfrog
  delete-artifacts:
    name: Delete artifacts
    uses: ./.github/workflows/delete-artifacts.yaml
