name: Pull `request open` stage build workflow (WIP)

on:
  pull_request:
    branches:
      - "stage*"
    types:
      - review_requested
  workflow_dispatch:

jobs:
  build-stage:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [21]
        include:
          - java-version: 21
            branch: "stage"
    with:
      java-version: ${{ matrix.java-verision }}
      branch: ${{ matrix.branch }}

  build-stage-jdk8:
    if: github.ref == 'refs/heads/stage-jdk8'
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [8]
        include:
          - java-version: 8
            branch: "stage-jdk8"
    with:
      java-version: ${{ matrix.java-version }}
      branch: ${{ matrix.branch }}

  delete-artifacts:
    name: Delete artifacts
    uses: ./.github/workflows/delete-artifacts.yaml
