name: Pull `request open` stage build workflow (WIP)

on:
  pull_request:
    branches:
      - stage
      - stage-jdk8
    types:
      - review_requested

jobs:
  build-stage:
    if: github.ref == 'refs/heads/stage'
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        java-version: [21]
        include:
          - java-version: 21
            branch: "stage"
    with:
      java-version: ${{ matrix.java-verision }}
      branch: ${{ matrix.branch }}
      build-identifier: "${{ matrix.java-version }}-${{ matrix.branch }}"
    #runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    java-version: [21]
    #    include:
    #      - java-version: 21
    #        branch: "stage"
    #steps:
    #  - name: Checkout client
    #    uses: actions/checkout@v2
    #    with:
    #      ref: ${{ matrix.branch }}
    #  - name: Setup Java

    #    uses: actions/setup-java@v4
    #    with:
    #      distribution: "semeru" # See 'Supported distributions' for available options
    #      java-version: ${{ matrix.java-version }}

    #  - name: Run EE server
    #    uses: ./.github/actions/run-ee-server
    #    #with:
    #    #  use-server-rc: ${{ inputs.use-server-rc }}
    #    #  server-tag: ${{ inputs.server-tag }}

    #  - name: Build and test
    #    run: |
    #      mvn install
    #      cd test
    #      mvn test -DskipTests=false

  build-jdk8:
    if: github.ref == 'refs/heads/jdk8'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [8]
        include:
          - java-version: 8
            branch: "jdk8"
    steps:
      - name: Checkout client
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "semeru" # See 'Supported distributions' for available options
          java-version: ${{ matrix.java-version }}

      - name: Run EE server
        uses: ./.github/actions/run-ee-server
        #with:
        #  use-server-rc: ${{ inputs.use-server-rc }}
        #  server-tag: ${{ inputs.server-tag }}

      - name: Build and test
        run: |
          mvn install
          cd test
          mvn test -DskipTests=false
