name: Pull `request open` stage build workflow (WIP)

on:
  pull_request:
    branches:
      - "stage*"
    types:
      - review_requested
  workflow_dispatch:

jobs:
  test-with-server-release:
    name: Build stage
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: ${{ github.ref }}

  test-with-server-rc:
    name: Build stage
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: ${{ github.ref }}
      use-server-rc: true
