name: Pull `request closed` stage build workflow (WIP)

on:
  pull_request_target:
    branches:
      - stage*
    types:
      - closed
  workflow_dispatch:

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: github.ref

  upload-to-jfrog:
    name: Upload artifacts to JFrog
    uses: ./.github/workflows/upload-to-jfrog.yml
    with:
      version: ${{ needs.bump-dev-number.outputs.new_version }}
    secrets: inherit

  # Clean up after files artifacts have been uploaded to jfrog
  delete-artifacts:
    needs: "build-stage"
    name: Delete artifacts
    uses: ./.github/workflows/delete-artifacts.yaml
