name: Pull `request open` stage build workflow

on:
  pull_request:
    branches:
      - "stage*"
    types:
      - review_requested
  workflow_dispatch:

jobs:
  test-with-server-release:
    name: Build stage - test with latest version of aerospike enterprise server
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: ${{ github.ref }}
    secrets: inherit

  test-with-server-rc:
    name: Build stage - test with latest RC version of aerospike enterprise server
    uses: ./.github/workflows/build-stage.yaml
    with:
      branch: ${{ github.ref }}
      use-server-rc: true
    secrets: inherit
