name: clients-java-push-to-dev

on:
  push:
    branches:
      - dev/*
  workflow_dispatch:

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/release-dev.yaml
    with:
      branch: ${{ github.ref }}
    secrets: inherit
