name: Promote

on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: ""
        type: string
        required: true
      target-branch:
        type: string
        required: true
        description: Target branch to promote token

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      # Needed since we are using  actions which are part of the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: "0"
          ref: ${{ inputs.target-branch }}
          token: ${{ secrets.CLIENT_BOT_PAT }}

      - name: Fast forward
        shell: bash
        run: git merge --ff-only ${{ inputs.commit-hash }}

      - name: Add tagging message
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Promote to prod [skip ci]"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          tagging_message: Promote to PROD
          branch: ${{ inputs.target-branch }}

      - name: Upload changes to remote head branch
        shell: bash
        run: git push

      - name: Get artifact version
        id: get-artifact-version
        working-directory: client
        run: |
          echo artifact-version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: ./.github/actions/github-release
        with:
          artifact-version: ${{ steps.get-artifact-version.outputs.artifact-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
